substitutions:
  devicename: outside
  max_run_duration: 60s
  sleep_duration: 60s

esp32:
  board: esp32dev
  framework:
    type: arduino

esphome:
  name: $devicename
  # on_boot documentation and priorities: https://esphome.io/components/esphome.html#on-boot
  on_boot:
    - priority: -100
      then: # At this priority, pretty much everything should already be initialized.
        # Have to make a delay otherwise api does not connect on time for some reason
        - logger.log: "Waiting to connect to api"
        - delay: 2s
        - logger.log: "Starting sensor updates..."
        - repeat:
            count: 5
            then:
              #Sensor updates are turned off and manually requested on boot. 
              #Then the ESP goes back to sleep when they're done (unless told to stay awake)

              # Request sensor updates
              - component.update: dht_outside
              - delay: 500ms # DHT11 is a really slow sensor
              - component.update: bmp_outside
              - delay: 100ms

  on_shutdown:
    priority: -100
    then:
      - if:
          condition:
            - binary_sensor.is_on: all_updates_received
          then:
            - logger.log: "Data from all sensors received"
          else:
            - logger.log: "One or more sensor updates missing"

      # Reset data update sensors states
      - binary_sensor.template.publish:
          id: temperature_dht_received
          state: OFF
      - binary_sensor.template.publish:
          id: humidity_dht_received
          state: OFF
      - binary_sensor.template.publish:
          id: temperature_bmp_received
          state: OFF
      - binary_sensor.template.publish:
          id: pressure_bmp_received
          state: OFF

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:

ota:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  id: wireless
#  manual_ip:
#    static_ip: 192.168.64.51
#    gateway: 192.168.64.1
#    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "esp-outside"
    password: "SioVN9kp2gvp"

captive_portal:
    
i2c:
  sda: 21
  scl: 22
  scan: true
  id: bus_a

deep_sleep:
  id: deep_sleep_1
  run_duration: $max_run_duration
  sleep_duration: $sleep_duration

#mqtt:
#  broker: 192.168.64.50
#  port: 1883
#  username: mqtt
#  password: mosquit69
#  birth_message:
#  will_message:
#  on_message:
#    - topic: esp32-outside/ota_mode
#      payload: 'ON'
#      then:
#        - deep_sleep.prevent: deep_sleep_1
#        - logger.log: "OTA mode enabled - deep sleep mode disabled"
#    - topic: esp32-outside/sleep_mode
#      payload: 'ON'
#      then:
#        - deep_sleep.enter: deep_sleep_1
#        - logger.log: "deep sleep mode enabled"

binary_sensor:
  # Data update sensors. Implemented as barrier. Huge thanks to user Mahko_Mahko on Home Assistant Community for providing his configuration example.
  # https://community.home-assistant.io/t/solar-powered-self-watering-plant-no-plumbing-no-power-wip/464263/14

  # outside temperature DHT
  - platform: template
    name: Temperature DHT updated
    id: temperature_dht_received
    internal: True 
    # Internal components will not be exposed to the frontend (like Home Assistant). 
    # Only specifying an id without a name will implicitly set this to true.
  # outside humidity DHT
  - platform: template
    name: Humidity DHT updated
    id: humidity_dht_received
    internal: True 
  # outside temperature BMP
  - platform: template
    name: Temperature BMP updated
    id: temperature_bmp_received
    internal: True
  # outside pressure BMP
  - platform: template
    name: Pressure BMP updated
    id: pressure_bmp_received
    internal: True 
  # All updates
  - platform: template
    name: Updates from all sensors received
    id: all_updates_received
    internal: True
    icon: mdi:database-refresh-outline
    # entity_category: diagnostic
    # If all sensors data is received. Will be false even if only one sensor fails.
    lambda: |-
      return id(temperature_dht_received).state && 
      id(humidity_dht_received).state && 
      id(temperature_bmp_received).state && 
      id(pressure_bmp_received).state;
    on_press:
    # Would this work with on_state as well?
      then:
        - delay: 100ms
        - script.execute: sleep_if_allowed
#        - deep_sleep.enter: 
#            id: deep_sleep_1
#        - script.execute: check_sensors_received

  # Import deep sleep switch from HA
  - platform: homeassistant
    name: "outside OTA mode"
    internal: false
    id: outside_ota_mode
    entity_id: input_boolean.outside_ota_mode
    # detect turn off ota while running
    on_state:
      then:
        - script.execute: sleep_if_allowed

script:
  - id: sleep_if_allowed
    then:
      - if:
          condition:
            - binary_sensor.is_on: all_updates_received
          then:
            - if:
                condition:
                  - binary_sensor.is_on: outside_ota_mode
                then:
                  - logger.log: "OTA mode enabled; preventing deep sleep"
                  - deep_sleep.prevent: deep_sleep_1
                else:
                  - logger.log: "OTA mode is disabled; entering deep sleep"
                  - deep_sleep.allow: deep_sleep_1
                  - deep_sleep.enter: deep_sleep_1
          else:
            - logger.log: "Not all sensors updates received yet. Retrying..."


sensor:
  - platform: uptime
    id: outside_uptime
    name: outside_uptime
    update_interval: 1s
    accuracy_decimals: 1
    unit_of_measurement: s
    internal: False

# DHT11 - temperature, humidity
  - platform: dht
    model: DHT11
    pin: 15
    id: dht_outside
    update_interval: never
    temperature:
      name: "outside temperature DHT"
      on_value:
        then:
          - binary_sensor.template.publish:
              id: temperature_dht_received
              state: ON
    humidity:
      name: "outside humidity DHT"
      on_value:
        then:
          - binary_sensor.template.publish:
              id: humidity_dht_received
              state: ON

  # BMP280 - temperature, pressure
  - platform: bmp280
    address: 0x76
    id: bmp_outside
    update_interval: never
    temperature:
      name: "outside temperature BMP"
      id: outside_termperature_bmp
      oversampling: 16x
      filters:
        - offset: -1.5
      on_value:
        then:
          - binary_sensor.template.publish:
              id: temperature_bmp_received
              state: ON
    pressure:
      name: "outside pressure BMP"
      on_value:
        then:
          - binary_sensor.template.publish:
              id: pressure_bmp_received
              state: ON